### PR TITLE
feat: replace `openssl` dependency with `sha2`

### PR DESCRIPTION
**Pull request by JarvisCraft**
# Description

This replaces `openssl` dependency with `sha2`
since the former is only used for calculating `sha2` hashes.

# Reasoning

There seems to be no need to depend on `openssl` crate to only calculate `sha2` hash.
Depensing on `openssl` is especially unpleasant
since it makes it harder to build self-contained statically linked binaries using MUSL.

# Alternatives

SHA256 implementation may be configurable via feature but it seems unreasonable considering its limited usage.

### CODE REVIEW

**Comment by divi255** [comment]
Good day,

sha2 crate is not FIPS 140-2 certified, that's why openssl is used. this can be switched using a feature but not replaced.

**Comment by JarvisCraft** [comment]
Thanks for your response! I will try to re-implement this using feature flags

**Comment by divi255** [comment]
merged, thanks. 0.1.6 uploaded

**Comment by JarvisCraft** [comment]
Great, thank you for such quick reaction!

I also suggest removing `Cargo.lock` from git since this is a library crate

**Pull request merged**
